version: '3'

services:
  bbjob_serv:
    image: bbjob_serv:0.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app/server
    command: [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0" ]

  bbjob_bot:
    image: bbjob_bot:0.0.1
    build:
      context: /app/telegram_bot
      dockerfile: Dockerfile_bot
    command: python bot.py
    working_dir: /app/telegram_bot

  bbjob_un:
    image: bbjob_un:0.0.1
    build:
      context: /app/telegram_bot
      dockerfile: Dockerfile_user_notifier
    command: python user_notifier.py
    working_dir: /app/telegram_bot



#  bbjob:
#    image: bbjob:0.0.1
#    ports:
#      - "8000:8000"
#    tty: true
#    stdin_open: true
#    build:
#      context: /app/backend
#      dockerfile: Dockerfile
#    command: uvicorn main:app --reload --host 0.0.0.0
#    working_dir: /app/backend


#cd /root/bbjob_ready && docker build -t bbjob_serv:0.0.1 .
#cd /root/bbjob_ready/app/telegram_bot && docker build -t bbjob_bot:0.0.1 -f Dockerfile_bot .
#cd /root/bbjob_ready/app/telegram_bot && docker build -t bbjob_un:0.0.1 -f Dockerfile_user_notifier .

